### ISSUE TITLE
Sanitize Exec / TryExec

### ISSUE THREAD

**Issue by jplatte** [DorianRudolph/sirula#2]
Currently, a bunch of apps for me shows up for me when just putting `app` in the search bar because they use `gapplication launch` for their `Exec` in the desktop file. It would be nice if the `gapplication launch` could be stripped, and only the remainder searched for a match. Similarily, `cups.desktop` has an `Exec` value of `/usr/bin/xdg-open http://localhost:631/` (and doesn't show up in sirula at all for some reason). I think Steam games would also be affected by this, universally showing up as the executable `steam` (though in that case I don't think it can be sanitized well).

![Screenshot_2020-08-06_115558](https://user-images.githubusercontent.com/951129/89519342-7db4cf80-d7dc-11ea-840a-6fe9570d7375.png)

Have set sirula as my default menu now by the way! :)

**Comment by DorianRudolph** [comment]
Awesome! CUPS does show up though, it is called "Manage Printing" (or "Druckverwaltung"). I think I need to rethink the search because right now I only use the executable name, not the entire command. And with CUPS the real name is only in the comment field. Using the entire Exec command and removing certain configurable terms might be one way (although CUPS will then still not be called CUPS). A configurable list with name overrides another. Other launchers just search everything I find it a little weird if you can't see what is matched. What do you think?

**Comment by jplatte** [comment]
Personally I don't care much about seeing what matched if the results, mostly importantly the first one, are good. For [caniuse.rs](https://caniuse.rs/) (which is of course also written in Rust – feel free to steal ideas from its search implementation :slightly_smiling_face:) I deliberately chose a matching design that would make it near impossible to highlight matches because I felt like it resulted in the best search results (although there's definitely still room for improvement).

One thing that you could also take into account in addition to the name and executable is the `.desktop` files basename.

**Comment by DorianRudolph** [comment]
That is a good idea. I made the small text configurable and added an option to add some hidden fields (see the default option file for documentation on that). I also added the option to override the name and extra text for individual apps.

**Comment by jplatte** [comment]
Whatever you did with `id_suffix` matching, it works great! I've removed the visible suffix and added hidden matching on that :slightly_smiling_face:
